name: flutter_tts_tizen_example
description: Demonstrates how to use the flutter_tts_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.0
  flutter_tts_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
