name: share_plus_tizen
description: Tizen implementation of the share_plus plugin
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SharePlusTizenPlugin
        fileName: share_plus_tizen_plugin.h        

dependencies:
  flutter:
    sdk: flutter
  share_plus_platform_interface: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
