name: device_info_tizen
description: Flutter plugin providing detailed information about Tizen device
  (make, model, etc.).
version: 2.0.2
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: DeviceInfoTizenPlugin
        fileName: device_info_tizen_plugin.h

dependencies:
  device_info_platform_interface: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
