name: image_picker_tizen
description: Tizen implementation of the image_picker plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/image_picker
version: 2.2.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: ImagePickerTizenPlugin
        fileName: image_picker_tizen_plugin.h
        dartPluginClass: ImagePickerTizen

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.6.2
