name: image_picker_tizen
description: Tizen implementation of the image_picker plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/image_picker
version: 2.3.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: ImagePickerTizenPlugin
        fileName: image_picker_tizen_plugin.h
        dartPluginClass: ImagePickerTizen

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.8.0
