name: image_picker_tizen
description: Flutter plugin for selecting images from the Tizen image
  library, and taking new pictures with the camera.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/blob/master/packages/image_picker
version: 2.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: ImagePickerTizenPlugin
        fileName: image_picker_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.0.1

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
