name: google_maps_flutter_tizen
description: Tizen implementation of the google_maps_flutter plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/google_maps_flutter
version: 0.1.11

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: GoogleMapsPlugin

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.10.0
  stream_transform: ^2.0.0
  webview_flutter: ^4.10.0
  webview_flutter_lwe: ^0.3.7
