name: device_info_plus_tizen
description: Flutter plugin providing detailed information about Tizen device
  (make, model, etc.).
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/device_info_plus
version: 1.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: DeviceInfoPlusTizenPlugin
        fileName: device_info_plus_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
