name: device_info_plus_tizen
description: Flutter plugin providing detailed information about Tizen device
  (make, model, etc.).
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: DeviceInfoPlusTizenPlugin
        fileName: device_info_plus_tizen_plugin.h

dependencies:
  device_info_plus_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
