name: sensors_example
description: Demonstrates how to use the sensors plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  sensors: ^2.0.0
  sensors_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
