name: url_launcher_tizen
description: Tizen implementation of the url_launcher plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/url_launcher
version: 2.1.4

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
  tizen_app_control: ^0.2.2
  url_launcher_platform_interface: ^2.3.2
