name: url_launcher_tizen
description: Tizen implementation of the url_launcher plugin
homepage: https://github.com/flutter-tizen/plugins
version: 1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: UrlLauncherPlugin
        fileName: url_launcher_tizen.dart

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: 1.0.8
  ffi: ^0.1.3
  meta: ^1.1.7

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0
  url_launcher: ^5.7.5

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
