name: share_tizen
description: Flutter plugin for sharing content via the platform share UI on Tizen.
version: 2.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: ShareTizenPlugin
        fileName: share_tizen_plugin.h        

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
