name: path_provider_tizen_example
description: Demonstrates how to use the path_provider_tizen plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.10
  path_provider_tizen:
    path: ../

dev_dependencies:
  integration_test: ^0.9.2
  integration_test_tizen:
    path: ../../integration_test/
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
