name: path_provider_tizen_example
description: Demonstrates how to use the path_provider_tizen plugin.
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  path_provider_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  permission_handler: ^8.1.3
  permission_handler_tizen:
    path: ../../permission_handler

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
