name: sensors_tizen
description: Tizen implementation of the sensors plugin
homepage: https://github.com/flutter-tizen/plugins
version: 2.0.2

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SensorsPlugin
        fileName: sensors_plugin.h

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
