name: sqflite_tizen_example
description: Demonstrates how to use the sqflite_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  path: any
  collection: any
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  sqflite_common:
  sqflite_tizen:
    path: ../
  synchronized:
  matcher:
  meta:

dev_dependencies:
  pedantic: ^1.11.0
  flutter_lints:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  test:
  process_run: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/example.db
    - assets/issue_64.db
