name: wifi_info_flutter_tizen_example
description: Demonstrates how to use the wifi_info_flutter_tizen plugin.
publish_to: 'none'

dependencies:
  connectivity: ^3.0.3
  connectivity_tizen:
    path: ../../connectivity/
  flutter:
    sdk: flutter
  wifi_info_flutter: ^2.0.0
  wifi_info_flutter_tizen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
