name: permission_handler_tizen
description: Tizen implementation of the permission_handler plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/permission_handler
version: 1.4.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: PermissionHandlerTizenPlugin
        fileName: permission_handler_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface: ^4.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
