name: wearable_rotary
description: Flutter plugin that can listen to rotary events on Wear OS and Tizen Galaxy watch devices.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/wearable_rotary
version: 2.0.4

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.samsung.wearable_rotary
        pluginClass: WearableRotaryPlugin
      tizen:
        pluginClass: WearableRotaryPlugin
        fileName: wearable_rotary_plugin.h

dependencies:
  flutter:
    sdk: flutter
