name: video_player_tizen
description: Tizen implementation of the video_player plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/video_player
version: 2.4.9

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h
        dartPluginClass: VideoPlayerTizen

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^5.1.2

dev_dependencies:
  pigeon: ^10.0.0
