name: video_player_example
description: Demonstrates how to use the video_player_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.2
  video_player_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  path_provider: ^2.0.6
  path_provider_tizen:
    path: ../../path_provider/
  test: any

flutter:
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
    - assets/Butterfly-209.webm
    - assets/bumble_bee_captions.srt
    - assets/bumble_bee_captions.vtt
    - assets/Audio.mp3
  uses-material-design: true
