name: audioplayers_tizen_example
description: Demonstrates how to use the audioplayers plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  audioplayers: ^6.1.0
  audioplayers_tizen:
    path: ../
  collection: ^1.16.0
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  http: ">=0.13.1 <2.0.0"
  path_provider: ^2.0.12
  path_provider_tizen:
    path: ../../path_provider/
  provider: ^6.0.5

dev_dependencies:
  flame_lint: ^0.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
  assets:
    - assets/
