name: package_info_plus_tizen
description: Tizen implementation of the package_info_plus plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/package_info_plus
version: 1.0.2

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: PackageInfoPlusTizenPlugin
        fileName: package_info_plus_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  package_info_plus_platform_interface: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
