name: webview_flutter_tizen
description: Tizen implementation of the webview plugin
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter
version: 0.3.9

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: ^1.2.0
  webview_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: WebviewFlutterTizenPlugin
        fileName: webview_flutter_tizen_plugin.h
        dartPluginClass: TizenWebView
