name: sensors_plus_example
description: Demonstrates how to use the sensors_plus plugin.
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^1.0.0
  sensors_plus_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.2
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
