name: geolocator_tizen
description: Tizen implementation of the geolocator plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/geolocator
version: 1.0.5

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: GeolocatorTizenPlugin
        fileName: geolocator_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  geolocator_platform_interface: ^3.0.0
