name: flutter_webrtc_demo
description: A new Flutter application.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.46
  flutter_webrtc_tizen:
    path: ../../
  http: ^0.13.3
  path_provider: ^2.0.7
  path_provider_tizen: ^2.1.0
  shared_preferences: ^2.2.0
  shared_preferences_tizen: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
