name: audioplayers_tizen
description: Tizen implementation of the audioplayers plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/audioplayers
version: 2.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: AudioplayersTizenPlugin
        fileName: audioplayers_tizen_plugin.h

dependencies:
  audioplayers_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.0
