name: audioplayers_tizen
description: Tizen implementation of the audioplayers plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/audioplayers
version: 3.0.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: AudioplayersTizenPlugin
        fileName: audioplayers_tizen_plugin.h

dependencies:
  audioplayers_platform_interface: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.0.0
