name: connectivity_plus_tizen
description: Tizen implementation of the connectivity_plus plugin.
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: ConnectivityPlugin
        pluginClass: ConnectivityPlusTizenPlugin
        fileName: connectivity_plus_tizen_plugin.h

dependencies:
  connectivity_plus_platform_interface: ^1.0.2
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
