name: tizen_notification
description: Tizen notification APIs. Used to show and delete notifications on a Tizen device.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_notification
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tizen_app_control: ^0.1.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: TizenNotificationPlugin
        fileName: tizen_notification_plugin.h
