name: share_example
description: Demonstrates how to use the share_tizen plugin.
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.3
  image_picker_tizen:
    path: ../../image_picker/
  share: ^2.0.1
  share_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
