name: google_sign_in_tizen
description: Tizen implementation of the google_sign_in plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/google_sign_in
version: 0.1.3

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: GoogleSignInTizen
  assets:
    - assets/images/qrcode.svg

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_secure_storage_tizen: ^0.1.0
  flutter_svg: ^1.1.5
  google_sign_in_platform_interface: ^2.3.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The example deliberately includes secrets.
false_secrets:
  - /example/lib/credentials.dart
