name: webview_flutter_lwe_example
description: Demonstrates how to use the webview_flutter_lwe plugin.
publish_to: "none"

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  path_provider_tizen:
    path: ../../path_provider/
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_lwe:
    path: ../
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  webview_flutter_platform_interface: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
