name: connectivity_tizen
description: Flutter plugin for discovering the state of the network (WiFi) connectivity on Tizen.
version: 2.0.1
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: ConnectivityTizenPlugin
        fileName: connectivity_tizen_plugin.h

dependencies:
  connectivity_platform_interface: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
