name: battery_tizen
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Tizen.
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: BatteryTizenPlugin
        fileName: battery_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
