name: battery_tizen
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Tizen.
version: 2.0.1
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: BatteryTizenPlugin
        fileName: battery_tizen_plugin.h

dependencies:
  battery_platform_interface: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
