name: sensors_plus_tizen
description: Tizen implementation of the sensors plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/sensors_plus
version: 1.2.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SensorsPlusPlugin
        fileName: sensors_plus_plugin.h

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_platform_interface: ^1.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
