name: sensors_plus_tizen
description: Tizen implementation of the sensors plugin
homepage: https://github.com/flutter-tizen/plugins
version: 1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SensorsPlusPlugin
        fileName: sensors_plus_plugin.h

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
