name: flutter_webrtc_example
description: Demonstrates how to use the webrtc plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background: ^1.0.0
  flutter_webrtc: ^0.9.27
  flutter_webrtc_tizen:
    path: ../../
  path_provider: ^2.0.7
  path_provider_tizen: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
