name: battery_example
description: Demonstrates how to use the battery plugin.

dependencies:
  flutter:
    sdk: flutter
  battery: ^1.0.7
  battery_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^0.9.2
  integration_test_tizen:
    path: ../../integration_test/
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
