name: geolocator_tizen_example
description: Demonstrates how to use the geolocator_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  baseflow_plugin_template: ^2.1.2
  cupertino_icons: ^1.0.1+1
  flutter:
    sdk: flutter
  geolocator: ^8.0.0
  geolocator_tizen:
    path: ../
  url_launcher_tizen:
    path: ../../url_launcher

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
