name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  camera: ^0.9.4
  camera_tizen:
    path: ../
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  path_provider_tizen:
    path: ../../path_provider
  video_player: ^2.1.4
  video_player_tizen:
    path: ../../video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test

flutter:
  uses-material-design: true
