name: flutter_secure_storage_tizen
description: Tizen implementation of the flutter_secure_storage plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_secure_storage
version: 0.1.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterSecureStorageTizenPlugin
        fileName: flutter_secure_storage_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
