name: path_provider_tizen
description: Tizen implementation of the path_provider plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/path_provider
version: 2.2.0

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: PathProviderPlugin

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  tizen_interop: ^0.3.0
