name: webview_flutter_tizen_example
description: Demonstrates how to use the webview_flutter_tizen plugin.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  path_provider_tizen:
    path: ../../path_provider/
  webview_flutter: ^4.0.2
  webview_flutter_tizen:
    path: ../

dev_dependencies:
  build_runner: ^2.1.5
  espresso: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  pedantic: ^1.10.0
    
flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
