name: flutter_tizen_plugin_tools
description: Productivity utils for flutter-tizen/plugins.
repository: https://github.com/flutter-tizen/plugins/tree/master/tools
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.1.0
  file: ^6.1.0
  flutter_plugin_tools: ^0.13.0
  http: ^0.13.3
  path: ^1.8.0
  platform: ^3.0.0
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.20.1
