name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  connectivity_plus: ^4.0.1
  connectivity_plus_tizen:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
