name: flutter_webrtc_tizen
homepage: https://github.com/flutter-tizen/plugins
description: Flutter WebRTC plugin for Tizen, based on GoogleWebRTC.
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_webrtc
version: 0.1.3

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterWebRtcTizenPlugin
        fileName: flutter_webrtc_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  path_provider_tizen: ^2.1.0
