name: tizen_app_manager_example
description: Demonstrates how to use the tizen_app_manager plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  device_info_plus_tizen:
    path: ../../device_info_plus/
  flutter:
    sdk: flutter
  tizen_app_control:
    path: ../../tizen_app_control/
  tizen_app_manager:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
