name: in_app_purchase_tizen
description: Tizen implementation of the in_app_purchase plugin for Samsung Smart TV.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/in_app_purchase
version: 0.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: InAppPurchaseTizenPlugin
        fileName: in_app_purchase_tizen_plugin.h
        dartPluginClass: InAppPurchaseTizenPlatform

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.0
  pigeon: ^22.4.2
