name: flutter_tts_tizen
description: The tizen implementation of flutter_tts plugin.
version: 1.0.1
homepage: https://github.com/flutter-tizen/plugins

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterTtsTizenPlugin
        fileName: flutter_tts_tizen_plugin.h

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
