name: Analyze

on: [push, pull_request]

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.1"
      - name: Install pub dependencies
        run: |
          for d in `pwd`/packages/*/; do
            cd $d
            flutter pub get
          done
      - name: Verify formatting
        run: flutter format --set-exit-if-changed packages
      - name: Analyze the plugin's Dart code
        run: |
          cd packages
          flutter analyze
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-11
      - name: Check tidy
        run: tools/run_command.py tidy --dir packages
