name: Analyze

on: [push, pull_request]

jobs:
  dart_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install pub dependencies
        run: |
          for d in `pwd`/packages/*/; do
            cd $d
            flutter pub get
          done
      - name: Analyze source code
        run: dart analyze --fatal-infos packages
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-11
      - name: Check format
        run: ./tools/tools_runner.sh format --fail-on-change
