# Copyright 2025 Samsung Electronics Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Find changed packages
        run: |
          CHANGED_PACKAGES=$(./tools/tools_runner.sh list \
            --run-on-changed-packages \
            --base-sha=$(git rev-parse HEAD^))
          if [[ ! -z $CHANGED_PACKAGES ]]; then
            echo $CHANGED_PACKAGES
            echo "HAS_CHANGED_PACKAGES=true" >> $GITHUB_ENV
          fi
      - name: Install Tizen Studio
        if: ${{ env.HAS_CHANGED_PACKAGES == 'true' }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y libncurses5 python2.7 libpython2.7 gettext \
            libkf5itemmodels5 libkf5kiowidgets5 libkchart2 dbus-x11 gnome-keyring
          curl https://download.tizen.org/sdk/Installer/tizen-studio_6.0/web-cli_Tizen_Studio_6.0_ubuntu-64.bin -o install.bin
          chmod a+x install.bin
          ./install.bin --accept-license $HOME/tizen-studio
          rm install.bin
      - name: Install Tizen Studio packages
        if: ${{ env.HAS_CHANGED_PACKAGES == 'true' }}
        run: |
          $HOME/tizen-studio/package-manager/package-manager-cli.bin install \
            NativeToolchain-Gcc-9.2 \
            IOT-Headed-6.0-NativeAppDevelopment-CLI \
            IOT-Headed-6.5-NativeAppDevelopment-CLI
      - name: Create a Tizen certificate profile
        if: ${{ env.HAS_CHANGED_PACKAGES == 'true' }}
        run: |
          export PATH=$PATH:$HOME/tizen-studio/tools/ide/bin
          dbus-run-session -- bash -c "
          echo tizen | gnome-keyring-daemon --unlock &&
          tizen certificate -a tizen -p tizen -f tizen
          tizen security-profiles add \
            -n tizen \
            -a $HOME/tizen-studio-data/keystore/author/tizen.p12 \
            -p tizen
          "
      - name: Install flutter-tizen
        if: ${{ env.HAS_CHANGED_PACKAGES == 'true' }}
        uses: actions/checkout@v3
        with:
          repository: flutter-tizen/flutter-tizen
          path: flutter-tizen
      - name: Build examples of changed packages
        if: ${{ env.HAS_CHANGED_PACKAGES == 'true' }}
        run: |
          export PATH=`pwd`/flutter-tizen/bin:$PATH
          dbus-run-session -- bash -c "
          echo tizen | gnome-keyring-daemon --unlock &&
          ./tools/tools_runner.sh build-examples \
            --exclude=wearable_rotary \
            --run-on-changed-packages \
            --base-sha=$(git rev-parse HEAD^)
          "
